### ISSUE TITLE
How can I check all my `>defn` via CLI?

### ISSUE THREAD

**Issue by khmelevskii** [gnl/ghostwheel#11]
Hello!
I use `shadow-cljs` and `deps.edn`. I need to run checking all my specs via CLI, because I want to run all test in CI. How can I do this?

**Comment by gnl** [comment]
Hey Yurii,

the checking in Ghostwheel is done through automatically generated regular `deftest`-based unit tests (`>defn` does that) which do spec-based generative testing when executed, so you can just run them like any other unit test with `(cljs.test/run-tests)` for any namespace where you're using Ghostwheel.

If you want to use the builtin custom reporter for better error messages, you can reference it with `(cljs.test/run-tests (cljs.test/empty-env :ghostwheel.reporting/default))` – presumably using whatever aliases you've set for the respective namespaces.

Do keep in mind though, that the reporter has been optimised for a browser-based JS console and may not look that great in a REPL/CLI environment. Fixing this is actually what I'm working on right now.

This section of the documentation will likely be relevant to you as well:
https://github.com/gnl/ghostwheel/blob/master/README.adoc#performance-considerations-or-how-much-generative-testing-is-enough

Please do not close this issue, even if this answers your question, because I'll want to add an additional note to the documentation about this.

**Comment by gnl** [comment]
There's also the `ghostwheel.core/check` macro, which is meant for testing after hot-reloading. It runs the tests as described above and does some additional coverage checks depending on the configuration, as well as instrumentation of external namespaces to catch incorrect calls during testing.

I think it still needs some love to be usable in a CI environment, but I'm looking into it as part of the current effort to make setting up a Ghostwheel-based test suite easy.

**Comment by markaddleman** [comment]
I'm eagerly looking forward to Ghostwheel working in a Clojure (not -script) REPL environment.  No need to respond.  I just want to express how exciting this project is.

**Comment by khmelevskii** [comment]
Thank you very much @gnl for you help. Everything works fine. Of course I will not close the task.  Indeed error messages in console doesn't look well. Btw how can I write down this
`(cljs.test/run-tests (cljs.test/empty-env :ghostwheel.reporting/default))`
in config `{:external-config {:ghostwheel {}}` in `shadow-cljs.edn`?

**Comment by gnl** [comment]
@markaddleman 

Thank you, Mark, I'll just say that the work that is being done now to implement proper reporting in the REPL/CLI and to make test execution in the REPL easy will most likely be fully cross-platform (I don't see a reason why it wouldn't, off the top of my head), so stay tuned – chances are pretty good that Clojure support will be in the next release.

@khmelevskii 
Possible misunderstanding - this is how you run the tests in the REPL or as part of your CI/test suite, after you've configured gen-testing correctly – it's not part of the configuration itself.

See step 5. here:
https://github.com/gnl/ghostwheel#getting-started

...as well as this:
https://github.com/gnl/ghostwheel#testing-specced-functions

But like I said, a better way to do this is coming up.

**Comment by gnl** [comment]
@khmelevskii 
In the new release you can now pass quoted function or namespace symbols to `(g/check)` to run any checks in the REPL. Also – regex. See the `g/check` parameters and docstring for details. If you want the output to also be in the REPL – rather than the JS console – you have to set `:report-output` to `:repl`.
See https://github.com/gnl/ghostwheel/blob/master/src/ghostwheel/utils.cljc#L21

`:repl` is the default on Clojure and cannot be changed. Speaking of which – @markaddleman – ta-daa! Clojure support.
