### ISSUE TITLE
>fdef doesn't work for me

### ISSUE THREAD

**Issue by khmelevskii** [gnl/ghostwheel#12]
I did something like this:
```
(ns app.foobar.test
  (:require
   [ghostwheel.core :refer [>fdef =>]]
   [app.foobar.hocs :as hocs]))

(>fdef
 hocs/my-func
 [arg]
 [int? => int?])
```

My config:
```
                            {:ghostwheel
                             {:check         true
                              :outstrument   true
                              :num-tests-ext 240
                              :ignore-fx     true}}
```

What am I doing wrong?

**Comment by gnl** [comment]
`(>fdef ...)` simply desugars to `(s/fdef...)` – at the moment it doesn't do any instrumentation or automatic test generation by design, only `(>defn...)` does. The main reason for `(>fdef...)`'s existence is to define fspecs for external libraries, so that they can be instrumented during testing or when developing/debugging.

**Comment by khmelevskii** [comment]
got it, thank you.
