### ISSUE TITLE
How can I exclude ghostwheel and its dependencies from production bundle 

### ISSUE THREAD

**Issue by khmelevskii** [gnl/ghostwheel#13]
Hello,
when I try to build app, where I required `ghostwheel` in result build file there are a lot of unnecessary libs:
https://www.dropbox.com/s/36lfkacdifns2gk/Screenshot%202018-09-22%2019.59.47.png?dl=0

As a result my prod app file has got much large size.

**Comment by gnl** [comment]
Hey Yurii,

originally there was some work being done to have an alternative ghostwheel-stubs artifact, similar to the way debux does it with https://github.com/philoskim/debux-stubs – it basically just desugared the Ghostwheel macros to plain defn, etc., but it was scrapped because I didn't think it was a clean approach and I didn't like it.

At the moment there are no plans to do this again, but I'll leave the issue open for people to upvote and I may reintroduce it at some point as an unofficial option if enough people are interested.

**Comment by gnl** [comment]
@khmelevskii 
Changed my mind: https://github.com/gnl/ghostwheel.stubs :) Also – the number of dependencies in the main ghostwheel artifact has been reduced significantly, so you may not even need the stubs, but just in case.

**Comment by khmelevskii** [comment]
@gnl wow, thank you! 👍
