### ISSUE TITLE
trace stops working in 0.3.5

### ISSUE THREAD

**Issue by dukefong8** [gnl/ghostwheel#18]
this line doesn't work in clj mode because ghostwheel.tracer is a cljs namespace.
https://github.com/gnl/ghostwheel/blob/3ef7e08aa8508210ab9b0dc4817e7c236bad9646/src/ghostwheel/core.cljc#L984

**Comment by gnl** [comment]
This is only checked in a cljs environment (strictly speaking in the clj-based macro evaluation build phase of a cljs project), but either way – tracing is the one thing that's not supported on Clojure, because Clairvoyant doesn't do Clojure (yet). Shouldn't be too much work to port it, especially now that tracing works in a cljs REPL environment, but it's not the highest priority.

So any work towards making that happen should start with submitting a Clojure-support PR to  https://github.com/Day8/clairvoyant (and its upstream repo).

**Comment by dukefong8** [comment]
That check broke ghostwheel.tracer cljs tracing in chrome as well since ghostwheel.tracer/tracer var is not visible at compile time when clj code run. Removing that line make it work again.
