### ISSUE TITLE
Does ghostwheel validate return values?

### ISSUE THREAD

**Issue by knubie** [gnl/ghostwheel#21]
I'm having trouble validating the return value of a function when it's called.

I have a function like:
```clojure
(>defn foo [x] [int? => int?]
  "foobar")
```

When I call it like this:
```clojure
(foo "x")
```
I get spec error about the argument as expected. However if I make the argument conform:
```clojure
(foo 1)
```
I don't get any error about the invalid return value. I do, however, get errors about the return value if I run the generative tests.

Is this expected behavior?

**Comment by gnl** [comment]
Looks like expected behaviour, assuming that you have enabled instrumentation with `::g/instrument`. In order to check the return value at runtime using spec-instrumentation you need to enable `::g/outstrument`. See https://github.com/gnl/ghostwheel/blob/master/src/ghostwheel/utils.cljc#L68
Let me know if this works.

**Comment by knubie** [comment]
@gnl Ah, that was it. I feel like I knew about the `:outstrument` option at one point but must have forgotten. Thanks for the help!
