### ISSUE TITLE
s/cat arg spec behaving incorrectly?

### ISSUE THREAD

**Issue by tslocke** [gnl/ghostwheel#25]
I have a function that expects a pair of keywords in one of the arguments, and I'm having a hard time getting a ghostwheel spec working. Here is a minimal repro:

    (>defn foo
      [x]
      [(s/cat :a keyword? :b keyword?) => any?]
      (first x))
    => #'test/foo__ghostwheel-test

    (foo [:x :y])

    Execution error - invalid arguments to test/foo at (form-init2634038421333083665.clj:1).
    form-init2634038421333083665.clj:1
    -- Spec failed --------------------
    Function arguments
      ([:x :y])
       ^^^^^^^
    should satisfy
      keyword?
    -------------------------
    Detected 1 error

Am I misunderstanding something here?

**Comment by gnl** [comment]
~You're not misunderstanding anything, you found a bug with nested `(s/cat ...)` specs when used unwrapped. :)~

The problem is that this particular gspec:
`[(s/cat :a keyword? :b keyword?) => any?]`

 eventually desugars to this fspec:

```
 (cljs.spec.alpha/fdef foo
   :args (cljs.spec.alpha/cat :x (s/cat :a keyword? :b keyword?))
   :ret any?)
```

`(s/cat ...)` is a regex op which does not start a new nested sequence on its own, so effectively the spec above would only match 2 keyword args, because your `s/cat` clause simply matches a non-nested subsequence within the arg vec.

I suspect the reason why this hasn't come up yet is that typically you'd do something like `(s/and vector? (s/cat...))` to be more specific and that would work fine, because `s/and` does start a new nested subsequence.

~That being said, your usage – while not recommended – is certainly perfectly valid and should work. I just fixed it and it'll be in the next release.~

**Comment by gnl** [comment]
...or in this case you should probably just use `(s/tuple keyword? keyword?)`

**Comment by gnl** [comment]
Now that I had a few minutes to look into it some more, I realise that it's actually a valid use case to have non-nested subsequences in a gspec, and if I were to wrap everything in `(s/spec ...)` to always force nesting they would break.

So I'm gonna have to backtrack on this and say that it's basically a spec issue and if you wanted to do what you're doing, you'd have to wrap the nested `s/cat` in `s/spec` to force the nesting.

See https://clojure.org/guides/spec#_sequences for more details on how that works.

But anyway, the spec I'd recommend in this case would be `(s/tuple keyword? keyword?)`

**Comment by tslocke** [comment]
`s/tuple` is perfect - I wasn't aware of that one. Thanks very much.
