### ISSUE TITLE
Empty error messages in browser console

### ISSUE THREAD

**Issue by armikhalev** [gnl/ghostwheel#9]
#### Description :octocat:

Empty Ghostwheel error message appears in browser console.

#### Reproduction guide :beetle:
Following the ReadMe:
- add `[gnl/ghostwheel "0.2.3"]` to project.clj (using Figwheel).
- add `#:ghostwheel.core{:check true, :num-tests 10}` to the namespace.
- add the following code taken from the ReadMe:
```Clojure

(>defn addition
  [a b]
  [pos-int? pos-int? => int? | #(> % a) #(> % b)]
  (+ a b))
```
- add `(ghostwheel/check)` at the end of the file.

*Observed behaviour:* :eyes: :broken_heart:
![ghostwheel-no-error](https://user-images.githubusercontent.com/13104390/44469297-2f10c980-a5f5-11e8-9487-7d403a556940.png)
(NOTE: `foo` and `ranged-rand` also from the docs, I just don't add them here)

*Expected behaviour:* :heart: :smile:
![no-error](https://user-images.githubusercontent.com/13104390/44469650-f2919d80-a5f5-11e8-9251-5c3d2e5ab25e.png)
(NOTE: Disregard the number of checks, it's just a pic from the ReadMe)

**Comment by armikhalev** [comment]
Apparently the issue is caused by presence of `[org.clojure/test.check "0.9.0"]` in `project.clj`. Removing it solves the problem!

**Comment by gnl** [comment]
Thank you Arseny, the problem here is that there were some breaking changes in `[org.clojure/test.check "0.10.0-alpha3"]` and after integrating that version in the last Ghostwheel release, it no longer works with an older one.

I'll add a note to the documentation that people should be careful not to override Ghostwheel's dependencies in their `project.clj`s.

**Comment by gnl** [comment]
Added note to the documentation.
